#data analysis project, letss  go

#question1: What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customertable
group by gender;

# Question 2: Which customers used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customertable
where discount_applied = "yes" and purchase_amount>=(select avg(purchase_amount) from customertable);


#Question 3: What are the top 5 products with the highest rating?
select item_purchased, round(avg(review_rating),2)
 as "Average Product Rating" 
from customertable
group by item_purchased
order by avg(review_rating) desc
limit 5;


#Question 4: Compare the average Puchase amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2)
from customertable
where shipping_type in ("Standard", "Express")
group by shipping_type;

#Question 5: Do subcribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customertable
group by subscription_status
order by total_revenue, average_spend desc;

#Question 6: which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(sum(case when discount_applied="Yes" then 1 else 0 END)/count(*)* 100,2) as discount_rate
from customertable
group by item_purchased
order by discount_rate desc
limit 5;

#Question 7: Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment
with customer_type as (
select customer_id, previous_purchases, 
case when previous_purchases=1 Then "New"
when previous_purchases between 2 AND 10 THEN "Returning"
else "Loyal"
end as customer_segment
from customertable)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

#Question 8: What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customertable
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

#Question 9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers 
from customertable
where previous_purchases>5
group by subscription_status;

#Question 10: What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue 
from customertable
group by age_group
order by total_revenue desc;